### ISSUE TITLE
“No spec found” is displayed after I use one jasmine reporter

### ISSUE THREAD

**Issue by johnysv** [stuisme/jasmine-pretty-html-reporter#6]
I am using jasmine-node framework for my API automation. I am able to run REST services and able to get the result using node-fetch or http. Without reporter when I run with the below command I was able to get the results in console

jasmine spec/xxx.spec.js

After that I added a reporter(pretty html reporter) for reporting. Now when I run those commands, I get the below error.

No specs found

Below are my code for reporter.js

var Jasmine = require('jasmine');
var HtmlReporter = require('jasmine-pretty-html-reporter').Reporter;
var path=require('path');
var jasmine = new Jasmine();

jasmine.loadConfigFile('./spec/support/jasmine.json');

// options object
jasmine.addReporter(new HtmlReporter({
  path: path.join('./spec/helpers','results')
}));

jasmine.execute();

and jasmine.json is below

{
  "spec_dir": "spec",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [
    "helpers/**/*.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": true
}

**Comment by stuisme** [comment]
Not sure exactly how your project is setup. But when running the spec from command line via `jasmine spec/xxx.spec.js` then jasmine is unaware of the `.addReporter(...)` call in `reporter.js`. However jasmine will still use `jasmine.json` at the root of the project.

I believe if you run `node <path to file>/reporter.js` it should work.
